In [ ]:

import pandas as pd

caminho = '/content/drive/MyDrive/Ciência de Dados/Vendas.csv'
arquivo = pd.read_csv(caminho)

In [ ]:
# 1. Exiba as 3 primeiras  linhas do DataFrame e verifique o nome de todas as colunas disponíveis.

# Exibe as 3 primeiras linhas
print("As 3 primeiras linhas:")
display(arquivo.head(3))

# Verifica o nome das colunas
print("\nNome das colunas:")
print(arquivo.columns)

As 3 primeiras linhas:

   ID_Venda  Produto  Faturamento  Quantidade        Data
0       101  Teclado        150.5           2  2024-01-01
1       102    Mouse         80.0           5  2024-01-01
2       103  Monitor       1200.0           1  2024-01-02

Nome das colunas:
Index(['ID_Venda', 'Produto', 'Faturamento', 'Quantidade', 'Data'], dtype='object')

In [ ]:
# 2. Descubra quantas vendas (linhas) foram registradas para cada produto.

# Conta a quantidade de vezes que cada produto aparece na tabela
contagem_produtos = arquivo['Produto'].value_counts()

# Exibe o resultado
print("Quantidade de vendas registradas por produto:")
print(contagem_produtos)

Quantidade de vendas registradas por produto:
Produto
Teclado    3
Mouse      3
Monitor    3
Cadeira    1
Name: count, dtype: int64

In [ ]:
# 3. Selecione apenas as vendas onde o Faturamento foi superior a R$ 500,00.

# Filtra as linhas onde o faturamento é maior (>) que 500
vendas_altas = arquivo[arquivo['Faturamento'] > 500]

# Exibe o resultado
print("Vendas com faturamento acima de R$ 500,00:")
display(vendas_altas)

In [ ]:
# 4. Identifique qual ID_Venda possui o faturamento ausente (NaN) e substitua esse valor por 0.

# Identifica e exibe a linha com o faturamento ausente (NaN)
print("Venda com faturamento ausente (antes da correção):")
display(arquivo[arquivo['Faturamento'].isna()])

# Substitui o valor ausente (NaN) por 0 de forma definitiva
arquivo['Faturamento'] = arquivo['Faturamento'].fillna(0)

print("\nValor ausente substituído por 0 com sucesso na tabela!")

Venda com faturamento ausente (antes da correção):

   ID_Venda Produto  Faturamento  Quantidade        Data
7       108   Mouse          NaN           4  2024-01-04

Valor ausente substituído por 0 com sucesso na tabela!

In [ ]:
# 5. Calcule a média de Quantidade vendida para cada tipo de Produto.

# Calcula a média da coluna 'Quantidade' para cada 'Produto'
media_quantidade = arquivo.groupby('Produto')['Quantidade'].mean()

# Exibe o resultado
print("Média de quantidade vendida por produto:")
display(media_quantidade)

Média de quantidade vendida por produto:

Produto
Cadeira    1.0
Monitor    1.0
Mouse      4.0
Teclado    2.0
Name: Quantidade, dtype: float64

In [ ]:
# 6. Agrupe os dados por Data e mostre o faturamento total de cada dia.

# Agrupa as vendas pela 'Data' e soma o 'Faturamento' de cada dia
faturamento_por_dia = arquivo.groupby('Data')['Faturamento'].sum()

# Exibe o resultado
print("Faturamento Total por Dia:")
display(faturamento_por_dia)

Faturamento Total por Dia:

Data
2024-01-01     230.5
2024-01-02    1280.0
2024-01-03    1350.5
2024-01-04     850.0
2024-01-05    1350.5
Name: Faturamento, dtype: float64

In [ ]:
# 7. Use o .iloc para selecionar apenas os dados da 5ª à 8ª linha (inclusive) e as colunas Produto e Faturamento.

# .iloc[linhas, colunas]
# Linhas 4:8 -> pega os índices 4, 5, 6 e 7 (que são da 5ª à 8ª linha na vida real)
# Colunas [1, 2] -> pega as colunas de índice 1 (Produto) e 2 (Faturamento)

recorte = arquivo.iloc[4:8, [1, 2]]

# Exibe o resultado
print("Dados da 5ª à 8ª linha (Apenas Produto e Faturamento):")
display(recorte)

Dados da 5ª à 8ª linha (Apenas Produto e Faturamento):

   Produto  Faturamento
4  Teclado        150.5
5  Monitor       1200.0
6  Cadeira        850.0
7    Mouse          0.0

In [ ]:
# 8. Crie uma nova coluna chamada Ticket_Medio que seja o resultado da divisão do Faturamento pela Quantidade. Apresente as duas primeiras linhas da tabela.

# Cria a nova coluna 'Ticket_Medio' dividindo o Faturamento pela Quantidade
arquivo['Ticket_Medio'] = arquivo['Faturamento'] / arquivo['Quantidade']

# Exibe apenas as 2 primeiras linhas para conferir o resultado
print("Tabela com a nova coluna Ticket_Medio:")
display(arquivo.head(2))

Tabela com a nova coluna Ticket_Medio:

   ID_Venda  Produto  Faturamento  Quantidade        Data  Ticket_Medio
0       101  Teclado        150.5           2  2024-01-01         75.25
1       102    Mouse         80.0           5  2024-01-01         16.00

In [ ]:
# 9. Converta a coluna Data para o tipo datetime e filtre apenas as vendas que ocorreram após o dia 02/01/2024.

# Converte a coluna 'Data' de texto para o formato oficial de data (datetime)
arquivo['Data'] = pd.to_datetime(arquivo['Data'])

# Filtra as linhas onde a Data é MAIOR (ou seja, depois) que 02/01/2024
# Nota: No Pandas, o padrão de data costuma ser Ano-Mês-Dia (YYYY-MM-DD)
vendas_recentes = arquivo[arquivo['Data'] > '2024-01-02']

# Exibe o resultado
print("Vendas que ocorreram após 02/01/2024:")
display(vendas_recentes)

Vendas que ocorreram após 02/01/2024:

   ID_Venda  Produto  Faturamento  Quantidade       Data  Ticket_Medio
4       105  Teclado        150.5           2 2024-01-03         75.25
5       106  Monitor       1200.0           1 2024-01-03       1200.00
6       107  Cadeira        850.0           1 2024-01-04        850.00
7       108    Mouse          0.0           4 2024-01-04          0.00
8       109  Monitor       1200.0           1 2024-01-05       1200.00
9       110  Teclado        150.5           2 2024-01-05         75.25

In [ ]:
# 10. Crie um ranking (do maior para o menor) que mostre o faturamento total por produto, mas apenas para aqueles que venderam mais de 3 unidades no total.

# Agrupa por produto e soma tanto o 'Faturamento' quanto a 'Quantidade'
resumo = arquivo.groupby('Produto')[['Faturamento', 'Quantidade']].sum()

# Filtra a tabela para deixar apenas quem vendeu mais (>) de 3 unidades
produtos_filtrados = resumo[resumo['Quantidade'] > 3]

# Ordena a tabela pelo Faturamento, do maior para o menor (ascending=False)
ranking = produtos_filtrados.sort_values(by='Faturamento', ascending=False)

# Exibe o ranking final (mostrando apenas a coluna de Faturamento para ficar limpo)
print("Ranking de Faturamento (Apenas produtos com > 3 unidades vendidas):")
display(ranking[['Faturamento']])

Ranking de Faturamento (Apenas produtos com > 3 unidades vendidas):

         Faturamento
Produto
Teclado        451.5
Mouse          160.0